version: '3.4'

services:

  postgres:
    image: postgres:14.1
    restart: always
    container_name: postgres
    command: postgres -c 'max_connections=400'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cubicfox
    ports:
      - "5433:5432"
    networks:
      - bmw-api

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ${PWD}/logs:/logs
    networks:
      - bmw-api
networks:
  bmw-api:
    driver: bridge